<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SDM.NativeHost</AssemblyName>
    <RootNamespace>SDM.NativeHost</RootNamespace>
    <Version>1.0.0</Version>
    <ApplicationIcon>..\SDM.App\Assets\sdm.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SDM.Core\SDM.Core.csproj" />
  </ItemGroup>
</Project>
